spring:
  application:
    name: eureka-client-product-info

server:
  port: 9030

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    seviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
